excludedPackages:
include:
allowedLicenses:
  - (AFL-2.1 OR BSD-3-Clause)
  - (MIT OR CC0-1.0)
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - CC-BY-3.0
  - CC-BY-4.0
  - CC0-1.0
  - ISC
  - MIT
  - MIT*
  - Python-2.0
  - Unlicense
