name: Makefile CI

on:
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: hcltm validate
        uses: xntrik/hcltm-action@latest
        with:
          command: validate
          files: "./threatmodels/*"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade pip
        run: |+
          pip install -U --progress-bar off --no-python-version-warning pip
          pip install -U --progress-bar off setuptools wheel

      - name: Install test dependencies
        run: pip install -U --progress-bar off pre-commit detect-secrets checkov

      - name: Run terraform checks
        run: |+
          TOOLS="terraform_checkov terraform_validate"
          for i in $TOOLS
          do
            pre-commit run $i --local-branch ${${{ github.event.pull_request.head.ref }}:-${{ github.ref }}}
          done

      - name: Check whitespace
        run: |+
          TOOLS="remove-tabs trailing-whitespace mixed-line-ending"
          for i in $TOOLS
          do
            pre-commit run $i --local-branch ${${{ github.event.pull_request.head.ref }}:-${{ github.ref }}}
          done

      - name: Run sca checks
        run: |+
          pre-commit run license-check-npm --local-branch ${${{ github.event.pull_request.head.ref }}:-${{ github.ref }}}

      - name: Run linting checks
        run: |+
          TOOLS="prettier typos check-json check-yaml"
          for i in $TOOLS
          do
            pre-commit run $i --local-branch ${${{ github.event.pull_request.head.ref }}:-${{ github.ref }}}
          done

      - name: Run secrets scanning
        run: |+
          TOOLS="detect-private-key detect-secrets"
          for i in $TOOLS
          do
            pre-commit run $i --local-branch ${${{ github.event.pull_request.head.ref }}:-${{ github.ref }}}
          done

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade pip
        run: |+
          pip install -U --progress-bar off --no-python-version-warning pip
          pip install -U --progress-bar off setuptools wheel

      - name: Install build dependencies
        run: pip install -U --progress-bar off mkdocs mkdocs-material mkdocs-material-extensions

      - name: hcltm build
        uses: xntrik/hcltm-action@latest
        with:
          command: dashboard
          files: "./threatmodels/*"
          outdir: "./src"

      - name: mkdocs build
        run: |+
          rm src/dashboard.md
          pre-commit run --verbose prettier --files src/*.md || true
          sed -i 's/|    |    |/| Attributes  |    |/g' src/*.md
          mkdocs build --strict --clean --verbose
          cp src/img/favicon.png dist/assets/images/favicon.png
